export const listTeamNacional= [
    {
        id:1,
        ruta:'katy-damacia-medina-marcos',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil-katy-medina.jpeg?alt=media&token=a41a306c-6b9b-4b8b-ab01-0ed2640847fa',
        name:'Katy Damacia Medina Marcos',
        cargo:'Investigadora principal',
        profesion:'Ingeniera Ambiental',
        ubicacion:'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        especialidad:'Máster universitario en Ecología, Gestión y Restauración del medio Natural en la especialidad de Gestión y Restauración del Medio Natural.',
        descripcion:'Magister-Ingeniera, con una formación sólida y científica, con estudios de pre grado en la Escuela Profesional de Ingeniería Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo y de post grado en la Universidad de Barcelona-España. Colegiada y habilitada en el Colegio de Ingenieros del Perú. Con dominio del idioma inglés nivel intermedio, alemán básico, conocimiento de manejo de base de datos MS Office, manejo de programas aplicados al Sistema de Información Geográfica (ArcGis y QGis), software como EQWin, R-Studio, SADA, Ginkgo y Primer&Permanova, experiencia en el monitoreo de la calidad ambiental del agua, suelo, sedimento y estudios glaciológicos y de teledetección.',
        correo:'mailto:kmedina@inaigem.gob.pe, katydamacia@hotmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=6141fb2af201987fbc14525feb91?id_investigador=45400',
        orcid:'https://orcid.org/0000-0002-2910-6808',
        researchgate:null
    },
    {
        id:2,
        ruta:'edwin-anibal-loarte-cadenas',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil-edwin-loarte.jpeg?alt=media&token=c6716974-9cb9-4b0c-be1b-36c7c8d700a2',
        name:'Edwin Aníbal Loarte Cadenas',
        cargo:'Co-investigador',
        profesion:'Ingeniero Ambiental',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        especialidad: 'Máster universitario en Gestión de Recursos Hídricos.',
        descripcion:'Profesional ligado a la investigación en recursos hídricos, glaciología, el cambio climático, conocimientos de análisis de riesgos sobre los ámbitos glaciares, simulación de desbordes de lagunas, con conocimiento de SIG y teledetección aplicados al estudio y monitoreo de los recursos ambientales, procesamiento de imágenes de satélite ópticas y radar. Estudios en gestión de recursos hídricos; capacitación en el campo de la glaciología e hidroglaciología, elaboración de balances de masa, determinación de líneas de equilibrio-ELA, determinación del área superficial, estimación de volúmenes, generación de índices de nieve-NDSI para coberturar área glaciar, índices de agua NDWI para coberturar lagunas, NDVI para coberturas de vegetación, experiencia en implementación de bases de datos espaciales e inventarios de lagunas.',
        correo:'mailto:e.loarte@inaigem.gob.pe, eloartecadenas@gmail.com',
        email:'Enviar correo',
        linkedin:'https://www.linkedin.com/in/edwin-loarte-cadenas-182b3153/',
        ctvitae: 'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=19929',
        orcid:'https://orcid.org/0000-0003-3123-1904',
        researchgate:null
    },
    {
        id:3,
        ruta:'hairo-alexander-leon-dextre',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_hairo_leon.png?alt=media&token=3dfa07fd-98d7-49de-aa24-168d8b74028b',
        name:'Hairo Alexander León Dextre',
        cargo:'Tesista de pregrado y asistente de investigación',
        profesion:'Ingeniero Ambiental',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        especialidad: 'Diplomado en Ordenamiento Territorial CELAEP - UNMSM y Especialización en Machine Learning con Pyhton - UPCH.',
        descripcion:'Ingeniero ambiental, con una formación sólida y científica, con dominio del idioma ingles nivel intermedio, francés básico, conocimiento de manejo de base de datos MS office, manejo de programas aplicados al Sistema de Información Geográfica (ArcGis, Terrset y Qgis), lenguajes de programación (R y python), experiencia en el monitoreo de la calidad ambiental del agua, suelo, fauna y flora, estudios relacionados a la gestión de recurso forestales y aplicaciones de teledetección para el estudio de los recursos naturales en zonas de alta montaña (glaciares, nieve, permafrost e hidrología).',
        correo:'mailto:hleond@unasam.edu.pe, alexanledex@gmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=144280',
        orcid:'https://orcid.org/0000-0003-2283-7584',
        researchgate:'https://www.researchgate.net/profile/Hairo-Leon'
    },
    {
        id:4,
        ruta:'sofia-cristina-rodriguez-venturo',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil-sofia-rodriguez.jpg?alt=media&token=9913577f-c546-41fd-9305-5815b428b35b',
        name:'Sofia Cristina Ana Rodriguez Venturo',
        cargo:'Asistente de investigación',
        ubicacion: 'Lima, Perú',
        universidad:'UNMSM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Bachiller en Microbiología y Parasitología',
        especialidad:'Especialización en Gerencia de Proyectos PMBOK - CTIC-UNI, Especialización en Patentes - INDECOPI y Estudiante de maestría en Biología Molecular - UNMSM.',
        descripcion:'Bachiller en Microbiología y Parasitología de la Universidad Nacional Mayor de San Marcos (UNMSM), con experiencia en estudios de ecología microbiana en ecosistemas altoandinos y desérticos. Conocimiento y manejo de técnicas moleculares y bioinformática.',
        correo:'mailto:sofia.rodriguez@unmsm.edu.pe, sofiarodven@gmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=48081',
        orcid:'https://orcid.org/0000-0002-0998-7222',
        researchgate:null
    },
    {
        id:5,
        ruta:'judy-maritza-salazar-alvaron',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_judy_salazar.jpeg?alt=media&token=c006759e-2080-48e0-8ba8-4c9bcf0d3826',
        name:'Judy Maritza Salazar Alvaron',
        cargo:'Coordinadora administrativa',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Licenciada en Contabilidad',
        especialidad: 'Maestría en Auditoría y Control de Gestión.',
        descripcion:'Contador público colegiado de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM), con experiencia profesional en el sector público y privado, en el manejo de recursos logísticos, financieros y humanos, con buen manejo de relaciones interpersonales, facilidad para trabajar en equipo en forma activa y concertada',
        correo:'mailto:coordinacion2.proyectos@inaigem.gob.pe',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:null,
        orcid:null,
        researchgate:null
    },
    {
        id:6,
        ruta:'edi-yocsari-septimo-villacaqui',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_edi_yocsari.jpeg?alt=media&token=4a7d0982-37ca-427b-8141-8daca3e7bedd',
        name:'Edi Yocsari Séptimo Villacaqui',
        cargo:'Coordinadora administrativa',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Licenciada en Contabilidad',
        especialidad: 'Diplomado en Gestión Administración y Gestión Pública.',
        descripcion:'Contador público, con experiencia profesional en el sector privado y público, en los temas tributarios (declaraciones de PDT621), elaboración de balance general de empresas del sector privado , elaboración de planilla, manejo de programas contables (Siscontsmart2021) y asistente administrativo.',
        correo:'mailto:yocsari95@gmail.com',
        email:'Enviar correo',
        linkedin:'https://pe.linkedin.com/in/edi-yocsari-septimo-villacaqui-8bb9b4149',
        ctvitae:null,
        orcid:null,
        researchgate:null
    },
    {
        id:7,
        ruta:'jean-pol-lujan-leon',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_pol_lujan.png?alt=media&token=745ba0a1-4530-4b87-a373-e73977464c6c',
        name:'Jean Pol Juniors Luján León',
        cargo:'Tesista de pregrado y gestor tecnológico',
        ubicacion:'Áncash, Perú',
        universidad:'UNFV',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Bachiller en Ingeniería Mecatrónica',
        especialidad:'Estudiante de la Diplomatura de Especialización Avanzada en Gestión de la Tecnología y de la Innovación (2021)-PUCP.',
        descripcion:'Bachiller en ingeniería mecatrónica  de la Universidad Nacional Federico Villarreal (UNFV), con experiencia en programación de controladores y diseño de sistemas de automatización. Conocimiento y desarrollo de tecnologias basadas en OpenSource.',
        correo:'mailto:jjlujanleon@gmail.com',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:'https://ctivitae.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=174289',
        orcid:'https://orcid.org/0000-0001-6161-8646',
        researchgate:null
    },
    {
        id:8,
        ruta:'ericsson-lorgio-lopez-vega',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_ericsson_lopez.jpeg?alt=media&token=bcb3cb19-5976-4c9e-ab2b-e8034faa5945',
        name:'Ericsson Lorgio Lopez Vega',
        cargo:'Tesista de pregrado',
        ubicacion: 'Lima, Perú',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Bachiller en Ingeniería Electrónica',
        especialidad: '',
        descripcion:'Profesional con interés y ganas de aportar en la mejora de la calidad de vida de las personas usando herramientas tecnológicas, ya que desde niño comprendí que la tecnología facilita y simplifica las actividades que realiza el hombre y permite la optimización del espacio, tiempo y recursos.',
        correo:'mailto:elopezv@uni.pe',
        email:'Enviar correo',
        linkedin:'https://pe.linkedin.com/in/ericsson-lopez-vega-1007',
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=194125',
        orcid:'https://orcid.org/0000-0002-9788-6682',
        researchgate:null
    },
    {
        id:9,
        ruta:'eduardo-emer-villavicencio-guillen',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil_Eduardo_Villavicencio.jpeg?alt=media&token=c3dccbfd-f391-4950-b144-512b084ece6f',
        name:'Eduardo Emer Villavicencio Guillén',
        cargo:'Tesista de postgrado',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Ingeniero Ambiental',
        especialidad:'Maestría en Recursos Hídricos.',
        descripcion:'Ingeniero Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM) con experiencia en el estudio de gestión de recursos hídricos, elaboración de balances de masa, determinación de líneas de equilibrio-ELA, generación de índices de nieve NDSI para coberturar área glaciar, lagunas y vegetación a través de técnicas de teledetección y fotogrametría.',
        correo:'mailto:e.villavicencio.guillen@gmail.com',
        email:'Enviar correo',
        linkedin:'https://www.linkedin.com/in/eduardo-villavicencio-77148421b',
        ctvitae:null,
        orcid:null,
        researchgate:null
    },
    {
        id:10,
        ruta:'edwin-noe-badillo-rivera',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil-edwin-badillo.jpeg?alt=media&token=227bff82-bc14-42e1-899b-93da3bdb2a91',
        name:'Edwin Noé Badillo Rivera',
        cargo:'Tesista de pregrado y Asistente de investigación',
        ubicacion: 'Lima, Perú',
        universidad:'Universidad Nacional del Callao',
        equipo:'EQUIPO INAIGEM',
        profesion: 'Bachiller en Ingeniería Ambiental y de Recursos Naturales',
        especialidad:'Especialización en "Python, Software Learning and Solutions" - Social Data Consulting SAC y Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM.',
        descripcion:'Bachiller en Ingeniería Ambiental y de Recursos Naturales (V superior), ligado al estudio de cambio climático y riesgos asociados a entornos de alta montaña. Conocimiento en tecnologías UAV, prospección geofísica, manejo de Tecnologías de Información Geográfica aplicados al estudio de recursos naturales y gestión del riesgo de desastres.',
        correo:'mailto:edbadillorivera@gmail.com',
        email:'Enviar correo',
        linkedin:'https://www.linkedin.com/in/edwin-no%C3%A9-badillo-rivera-459b12150/',
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=81e887f7559aadbc42631d268af5?id_investigador=80560',
        orcid:'https://orcid.org/0000-0003-2127-3895',
        researchgate:'https://www.researchgate.net/profile/Edwin-Badillo-Rivera'
    },
    {
        id:11,
        ruta:'francisco-nemecio-castillo-vergara',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2FProfesional-francisco-castillo.jpeg?alt=media&token=e8e437b8-09f5-495f-aa0d-59efaf3d4d86',
        name:'Francisco Nemecio Castillo Vergara',
        cargo:'Tesista de postgrado',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Ingeniero Ambiental',
        especialidad:'Especialización en "Modelamiento hidraulico e hidrologico" - CELAEP-UNMSM y Estudios finalizados en maestría en "Ciencias e Ingeniería con mención en Gestión Ambiental" - UNASAM.',
        descripcion:'Ingeniero Ambiental de la Universidad Nacional Santiago Antúnez de Mayolo (UNASAM V superior), dedicado al uso de las herramientas de teledetección y los sistemas de información geográfica. Asistente de investigación en temáticas relacionadas a glaciares y ecosistemas de montaña.',
        correo:'mailto:fcastillouv@unasam.edu.pe',
        email:'Enviar correo',
        linkedin:null,
        ctvitae:'https://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do;jsessionid=351770571c155d27537e1a415bed?id_investigador=145013',
        orcid:'https://orcid.org/0000-0002-6799-3495',
        researchgate:null
    },
    {
        id:12,
        ruta:'alexzander-santiago-martel',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Finaigem%2Fperfil-aleksander-santiago.png?alt=media&token=bbaad969-eded-47a0-9551-fc9c264629b9',
        name:'Alexzander Santiago Martel',
        cargo:'Tesista de posgrado',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO INAIGEM',
        profesion:'Ingeniero Ambiental',
        especialidad:'Especialista en Geomática.',
        descripcion:'Ingeniero Ambiental, con conocimiento en temas de Geomática aplicados a Glaciares y Ecosistemas de montaña. Elaborando una investigación en temas de variación de la superficie del Glaciar Pastoruri empleando tecnología RPA (remotely piloted aircraft); a la vez se participó como coautor en investigaciones relacionados a la estimación de volumen glaciar de la cordilleras de Perú presentado en la EGU (poster ), presentación de la investigación (coautor) en el simposio brasileño con el paper "Influencia de los parámetros climáticos sobre la variación de la cobertura vegetal en la laguna Conococha, utilizando técnicas de percepción remota". Investigación en el cálculo de volumen de la laguna Safuna Alta, empleando técnicas de teledetección, realizada para optar el titulo procesional de Ingeniero Ambiental.',
        correo:'mailto:asantiagom@unasam.edu.pe',
        email:'Enviar correo',
        linkedin:'https://www.linkedin.com/in/v%C3%ADctor-smith-medina-cotrina-28155159/',
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=105469',
        orcid:'https://orcid.org/0000-0003-0247-7294',
        researchgate:null
    },
    {
        id:13,
        ruta:'jorge-luis-mirez-tarrillo',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Funi%2Fperfil_jorge_mirez.jpeg?alt=media&token=a6bcb0ed-72fa-4aed-8005-b957cc0336a7',
        name:'Jorge Luis Mirez Tarrillo',
        cargo:'Co-investigador',
        ubicacion: 'Lima, Perú',
        equipo:'EQUIPO UNI',
        universidad:'Universidad Nacional Pedro Ruiz Gallo',
        profesion: 'Ingeniero Mecánico Electricista',
        especialidad:'Miembro del comité Editorial Revista "Perfiles" - Escuela Superior Politécnica de Chimborazo - Ecuador.',
        descripcion:'Soy Ingeniero Mecánico Electricista por la Universidad Nacional "Pedro Ruíz Gallo" (Lambayeque, Perú), además Maestro en Ciencias con mención en Física y Doctor en Ciencias con mención en Física en la Universidad Nacional de Ingeniería (UNI) en Lima, Perú. Como profesional me he desempeñado en la docencia universitaria e investigación en universidades públicas y privadas, también como ingeniero y consultor en hospitales e instituciones anexas al Ministerio de Salud del Perú desde el año 2000 y además como consultor independiente en temas de energía, ingeniería e investigación. Mi investigación está enfocada en los sistemas eléctricos y las energías renovables. Actualmente mi principal principal tema de investigación es sobre el control, optimización y gestión de microredes de energía de corriente continua (DC MG) que son sistemas eléctricos inteligentes que pueden trabajar conectados o aislados de la red eléctrica pública y que tienen microfuentes de generación eléctrica (solar fotovoltaica, eólica), almacenamiento de energía eléctrica (baterías), y cargas eléctricas, para ello emulo el comportamiento biológico. Otros temas de mi interés es el modelamiento matemático y simulación numérica en ciencias e ingeniería, enfocándome principalmente en ingeniería biomédica, ingeniería espacial y energías renovables. Uso el software Matlab/Simulink de MathWorks Inc y parte de mis lecturas y avances lo difundo a través de redes sociales: Fanpage, Facebook, Twitter, y varios blogs en Wordpress. Research Interests Applied Mathematics & Computational Science: Control Theory and Stochastic Systems Modeling Physical/Biological Phenonema and Systems Electrical Engineering: Biological & Artificial Systems: Lidero el Grupo de Modelamiento Matemático y Simulación Numérica - GMMNS de la Universidad Nacional de Ingeniería - UNI en Lima, Perú. GMMNS está registrado en la plataforma de grupos de investigación.',
        correo:'mailto:ctic@uni.edu.pe',
        email:'Enviar correo',
        linkedin:'https://pe.linkedin.com/in/jorge-luis-mirez-tarrillo-94918423',
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=10642',
        orcid:'https://orcid.org/0000-0002-5614-5853',
        researchgate:null,
    },
    {
        id:14,
        ruta:'alfredo-walter-reyes-nolasco',
        name:'Alfredo Walter Reyes Nolasco',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Fnacional%2Funasam%2Fperfil_alfredo_reyes.png?alt=media&token=6f781b59-1279-438c-8def-bc2a1964eb75',
        cargo:'Co-Investigador',
        ubicacion: 'Áncash, Perú',
        universidad:'UNASAM',
        equipo:'EQUIPO UNASAM',
        profesion: 'Ingeniero Agrónomo',
        especialidad:'Especialista en  interpretación de imágenes de sensores remotos aplicados a levantamientos edafológicos del Instituto Geográfico Agustín Codazzi Bogotá, Colombia.',
        descripcion:'Magister Scientiae en Suelos de la Universidad Nacional Agraria La Molina (UNALM). Dr.  en Ingeniería Ambiental. Experiencia en mapeo y cartografía de suelos y evaluación de tierras de diverso orden, estudios de la contaminación de suelos y aguas en el contexto de la litología, cambio climático y el retroceso glaciar.',
        correo:'mailto:areyesn@unasam.edu.pe',
        email:'Enviar correo',
        linkedin:'https://pe.linkedin.com/in/alfredo-reyes-nolasco-50132918',
        ctvitae:'http://dina.concytec.gob.pe/appDirectorioCTI/VerDatosInvestigador.do?id_investigador=36903',
        orcid:'https://orcid.org/000000022651841X',
        researchgate:null
    },
]

export const listTeamInternacional = [
    {
        id:1,
        ruta:'christian-huggel',
        name: 'Christian Huggel',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Finternacional%2Fperfil-christian-huggel.jpeg?alt=media&token=2364ae8c-484a-4df6-baed-047243d126d1',
        cargo:'Co-Investigator',
        ubicacion:'Suiza',
        profesion:'Professor Glaciology and Geomorphodynamics',
        equipo:'INTERNATIONAL TEAM',
        especialidad:'PhD.',
        descripcion:'My research focus on climate impacts, risks and adaptation to climate change implies working at the intersection of several scientific disciplines. This is also reflected in my biography, for instance with a publication record in more than 30 different peer-reviewed journals; or by chairing a number of international scientific joint commissions of different science associations (IACS, IPA, IAVCEI), such as the one on glacier and permafrost hazards in mountains (GAPHAZ) and on ice-volcano interactions. Currently I’m a member of scientific advisory boards or committees such as for the Mountain Research Initiative (MRI), or the Swiss Federal Environmental Research (OFU), or UZH Center of Competence Center for Sustainable Finance. I’ve been also working for many years at the intersection of science and international climate policy, including currently as a lead author for the IPCC 6th Assessment Report (AR6) and previously for AR5 (2010-2014).',
        correo:'mailto:christian.huggel@geo.uzh.ch',
        email:'Send mail',
        geouzh:'https://www.geo.uzh.ch/~chuggel/',
        uzh:'https://www.geo.uzh.ch/en/department/Staff/christianhuggel',
        eclim:'https://eclim-research.ch/team/christian-huggel/',
        hud:null,
        edytem:null,
        researchgate:'https://www.researchgate.net/profile/Christian-Huggel',
        savoie:null,
        geocriologia:null,
        orcid:null,
        linkedin:null,
    },
    {
        id:2,
        ruta:'wilson-ryan',
        name: 'Wilson Ryan',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Finternacional%2Fperfil_ryan_wilson.webp?alt=media&token=836989c6-b3d6-4ee2-a2c0-f80ba97e554b',
        cargo:'Co-Investigator',
        ubicacion: 'United Kingdom',
        profesion:'Senior Lecturer in Physical Geography',
        equipo:'INTERNATIONAL TEAM',
        especialidad:'PhD.',
        descripcion:'His research activities are centred on the monitoring of the cryosphere using GIS and remote sensing datasets with the aim of achieving a better understanding of past, present and future change and its subsequent impacts on the environment. Between 2016 to 2018, Ryan worked as a post-doctoral researcher on the NERC/CONICYT funded “Glacial hazards in Chile” project (NE/N020693/1) being responsible for the processing and analysis of satellite- and UAV-derived geospatial datasets.',
        correo:'mailto:r.wilson2@hud.ac.uk',
        email:'Send mail',
        geouzh:null,
        uzh:null,
        eclim:null,
        hud:'https://pure.hud.ac.uk/en/persons/ryan-wilson',
        edytem:null,
        researchgate:null,
        savoie:null,
        geocriologia:null,
        orcid:null,
        linkedin:null,
    },
    {
        id:3,
        ruta:'florence-magnin',
        name: 'Florence Magnin',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Finternacional%2Fperfil_florence_magnin.jpeg?alt=media&token=94c43af5-84fa-4446-84ec-4766ac189071',
        cargo:'Co-Investigator',
        ubicacion:'Chambéry, France',
        profesion:'Geomorphology Specialist',
        equipo:'INTERNATIONAL TEAM',
        especialidad:'PhD.',
        descripcion:'I am a researcher at the EDYTEM laboratory (CNRS-Université Savoie Mont Blanc) in France. I am specialized in periglacial geomorphology and permafrost dynamics in steep rock slopes. I mostly work on trying to understand how steep rock slope permafrost respond to climate change on various time and space scales, and trying to understand the steep slope permafrost processes that lead to rock slope destabilisations. I mainly use in-situ temperature measurements, electrical resistivity tomography, GIS mapping, statistical and numerical modeling to assess permafrost distribution, simulate its processes and determine areas that may become unstable or may be impacted by rock slope failures occuring in high mountain.',
        correo:'mailto:florence.magnin@geo.uio.no',
        email:'Send mail',
        geouzh:null,
        uzh:null,
        eclim:null,
        hud:null,
        edytem:'https://edytem.cnrs.fr/pages-personnelles/florence-magnin/',
        researchgate:'https://www.researchgate.net/profile/Florence-Magnin-2',
        savoie:null,
        geocriologia:null,
        orcid:null,
        linkedin:null,
    },
    {
        id:4,
        ruta:'xavier-bodin',
        name: 'Xavier Bodin',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Finternacional%2Fperfil_xavier_bodin.jpeg?alt=media&token=6b213db0-6e3f-427e-8a7c-aed507da2cbe',
        cargo:'Co-Investigator',
        ubicacion:'Chambéry, France',
        profesion:'Geomorphology Specialist',
        equipo:'INTERNATIONAL TEAM',
        especialidad:'PhD.',
        descripcion:'Geomorfología periglacial, ambientes de alta montaña (Alpes, Andes), dinámica de glaciares de escombros, degradación del permafrost.',
        correo:'mailto:xavier.boin@univ-smb.fr',
        email:'Send mail',
        geouzh:null,
        uzh:null,
        eclim:null,
        hud:null,
        edytem:null,
        researchgate:null,
        savoie:'https://univ-savoie.academia.edu/XavierBodin',
        geocriologia:'http://www.geocriologia.com.ar/quienes-somos/bodin-xavier',
        orcid:'https://orcid.org/0000-0001-6245-4030',
        linkedin:null,
    },
    {
        id:5,
        ruta:'guillermo-azocar',
        name: 'Guillermo Azócar Sandoval',
        foto:'https://firebasestorage.googleapis.com/v0/b/proyecto-permafrost-45b38.appspot.com/o/equipo-cientifico%2Finternacional%2Fperfil_guillermo_azocar.jpg?alt=media&token=07f18fbc-f209-4e1c-833f-85ffdb26c3f0',
        cargo:'Co-Investigador',
        ubicacion: 'Santiago, Chile',
        profesion:'Licenciado en Geografía',
        equipo:'INTERNATIONAL TEAM',
        especialidad:'M.Sc. en Geografía de la Universidad de Waterloo.',
        descripcion:'Geografó de la Universidad de Chile y  M.Sc. en Geografía de la Universidad de Waterloo, Canadá. Actualmente ejerce como director de proyectos en la empresa Atacama Ambiente Consultores.   Como consultor ambiental ha trabajo en los ultimos 12 años diversos proyectos públicos y privados sobre el estudio del ambiente periglacial, permafrost de montaña y de glaciares blancos tanto en Chile como en Perú.  En temas de investigación cientifica mantiene un gran interes en  el estudio de geomorfologías periglaciales, análisis espacial y de ambientes de montaña, especialmente permafrost y glaciares rocosos, ademas del mejoramiento de los métodos de monitoreos de los ambiente de montaña. Guillermo ha contribuido como autor y coautor de publicaciones científicas sobre temas relacionados a la distribución de glaciares rocosos, permafrost e impacto ambiental minero, entre otros temas.',
        correo:'mailto:Gazocar@atacamamb.com',
        email:'Send mail',
        geouzh:null,
        uzh:null,
        eclim:null,
        hud:null,
        edytem:null,
        researchgate:'https://www.researchgate.net/profile/Guillermo-Azocar-Sandoval',
        savoie:null,
        geocriologia:null,
        orcid:'https://orcid.org/0000-0002-5455-2842',
        linkedin:'http://www.linkedin.com/in/gmoazocar',
    }
]