export const listaPT1 = [
    {
        id:1,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Caraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con la población de la unidad hidrográfica Llullán realizado en la ciudad de Caraz teniendo como expositor al co-investigador Fernando González de la entidad asociada de la PUCP.',
        lugar:'Unidad hidrográfica Llullán	',
        fecha:'Jun, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F2.taller_llull%C2%A0n.JPG?alt=media&token=0642ecb3-0bcd-4c18-b30a-1ca04e83e305',
        cover:"cover"
    },
    {
        id:2,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz teniendo como expositores a los investigadores principales Edwin Loarte y Francesca Pelliciotti.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.Workshop_taller_centro_cultural.jpg?alt=media&token=48d33f74-fa21-49b1-8808-a93b13330b02',
        cover:"cover"
    },
    {
        id:3,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.Workshop_taller_centro_cultural3.jpg?alt=media&token=09341e2c-15ee-45e6-9f50-bae3de072009',
        cover:"cover"
    },
    {
        id:4,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Cátac",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidad hidrográfica Yanayacu realizado en el auditorio de la Municipalidad Distrital de Cátac.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac.JPG?alt=media&token=ab86394e-216d-42af-9f33-fd0e7afc1356',
        cover:"cover"
    },
    {
        id:5,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Cátac",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidad hidrográfica Yanayacu realizado en el auditorio de la Municipalidad Distrital de Cátac.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac3.JPG?alt=media&token=407ba6b2-a766-476b-8f74-54ed59136aee',
        cover:"cover"
    },
    {
        id:6,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Camino a Pastoruri",
        descripcion:'Taller de campo de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el ruta del cambio climático del nevado Pastoruri.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac4.JPG?alt=media&token=251160a5-44d3-44cc-a72a-a25065778b69',
        cover:"cover"
    },
    {
        id:7,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2FWorkshop_taller_centro_cultural2.jpeg?alt=media&token=66d14447-e3fc-483a-b791-087606485d7e',
        cover:"cover"
    },
    {
        id:8,
        nombre:'Monitoreo de la calidad de agua',
        titulo:"MONITOREO DE LA CALIDAD DE AGUA",
        subTitulo:"Río de Artesoncocha Alta",
        descripcion:'Monitoreo de la calidad de agua en la parte media del río que fluye de la laguna en formación al pie del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán ',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F1.Calidad_Artesonraju_PT1.jpg?alt=media&token=27a4fe19-bef3-4b0f-8cdf-794eb5376c85',
        cover:"cover"
    },
    {
        id:9,
        nombre:'Monitoreo de la calidad de agua',
        titulo:"MONITOREO DE LA CALIDAD DE AGUA",
        subTitulo:"Laguna Artesoncocha Alta",
        descripcion:'Monitoreo de la calidad de agua en la laguna en formación al pie del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán ',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F4.Calidad_Artesonraju_PT1.JPG?alt=media&token=e9b8bbc8-7bb6-4335-a618-971319132688',
        cover:"cover"
    },
    {
        id:10,
        nombre:'Muestreo de macroinvertebrados',
        titulo:"MUESTREO DE MACROINVERTEBRADOS",
        subTitulo:"Río de Llaca",
        descripcion:'Muestreo de macroinvertebrados con el uso de una malla surber en el río de salida de la laguna Llaca para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F4.MacroinvertebradosLlaca_PT1.JPG?alt=media&token=f978a311-42c7-4de7-b534-345c50ae7c43',
        cover:"cover"
    },
    {
        id:11,
        nombre:'Muestreo de macroinvertebrados',
        titulo:"MUESTREO DE MACROINVERTEBRADOS",
        subTitulo:"Río de Pamparaju",
        descripcion:'Muestreo de macroinvertebrados con el uso de una malla surber en el río de salida de la laguna Pamparaju para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.MacroInv_Gueshgue20_PT1.JPG?alt=media&token=fa922fb1-264b-411d-bd75-70112510cc85',
        cover:"cover"
    },
    {
        id:12,
        nombre:'Muestreo de algas y diatomeas',
        titulo:"MUESTREO DE ALGAS Y DIATOMEAS",
        subTitulo:"Río de Pamparaju",
        descripcion:'Muestreo de algas y diatomeas en el río de salida de la laguna Pamparaju para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F8.Diatomeas_Gueshgue20_PT1.JPG?alt=media&token=f06fb4e5-77f9-4a10-a628-0e1eb46580dd',
        cover:"cover"
    },
    {
        id:13,
        nombre:'Muestreo de algas y diatomeas',
        titulo:"MUESTREO DE ALGAS Y DIATOMEAS",
        subTitulo:"Río de laguna en formación de Gueshgue",
        descripcion:'Muestreo de algas y diatomeas en el río de salida de la laguna en formación al pie del glaciar Gueshgue para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F10.Diatomeas_Gueshgue20_PT1.JPG?alt=media&token=378e30c7-3da9-4fea-9acd-028556507650',
        cover:"cover"
    },
]   

export const listaPT2 = [
    {
        id:1,
        nombre:'Medición de espesor de hielo (GPR)',
        titulo:"MEDICIÓN DE ESPESOR DE HIELO (GPR)",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Medición del espesor de hielo usando el equipo radar de penetración terrestre (GPR) en la superficie del glaciar limpio de Gueshgue (parte media) para el monitoreo de la variación de la profundidad del hielo glaciar y su potencial de reserva hídrica (año 2021).',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F10.GPR_Gueshgue21.JPG?alt=media&token=9c33198d-0e1c-467d-9e76-cc67cdd8948d',
        cover:"cover"
    },
    {
        id:2,
        nombre:'Instalación de balizas',
        titulo:"INSTALACIÓN DE BALIZAS",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Instalación de balizas en la zona de ablación en la parte media del glaciar Gueshgue para el monitoreo glaciológico.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F2.BalizasArtesonraju_PT2.JPG?alt=media&token=bce50076-deb8-4e1a-a5f1-51289720fc11',
        cover:"cover"
    },
    {
        id:3,
        nombre:'Medición de espesor de hielo (GPR)',
        titulo:"MEDICIÓN DE ESPESOR DE HIELO (GPR)",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Medición del espesor de hielo usando el equipo radar de penetración terrestre (GPR) en la superficie del glaciar limpio de Gueshgue (parte media) para el monitoreo de la variación de la profundidad del hielo glaciar y su potencial de reserva hídrica (año 2020).',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F4.GPRGueshgue3.JPG?alt=media&token=764bbac4-348c-49d9-bf20-92b2a45b1b98',
        cover:"cover"
    },
    {
        id:4,
        nombre:'Fotogrametría aérea RPA (dron)',
        titulo:"FOTOGRAMETRÍA AÉREA RPA (DRON)",
        subTitulo:"Glaciar Shallap",
        descripcion:'Fotogrametría aérea RPA (dron) en la parte alta del glaciar Shallap para el monitoreo de la dinámica de la lengua glaciar limpia y cubierta de detritos y escombros.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F5.FotogAerea_Shallap_PT2.jpg?alt=media&token=c10010c6-81b4-4d87-9674-555c90d05d8c',
        cover:"cover"
    },
    {
        id:5,
        nombre:'Instalación de estación meteorológica ',
        titulo:"INSTALACIÓN DE ESTACIÓN METEOROLÓGICA",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Instalación y configuración de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglacial del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2FMantEM_PT2.jpg?alt=media&token=cb83dd4b-35e5-4d50-a7d4-24b61f3458ff',
        cover:"cover"
    },
    {
        id:6,
        nombre:'Medición de caudales ',
        titulo:"MEDICIÓN DE CAUDALES",
        subTitulo:"Río de Artesoncocha Alta",
        descripcion:'Medición de caudales del río proveniente del desemboque de la laguna en formación al pie del glaciar Artesonraju, a través del método del correntómetro para la recolección de datos para el modelamiento hidrológico.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.Aforo_correntometro_Artesonraju2021_PT2.jpg?alt=media&token=630fe517-3ea0-48c5-8c42-f10a5520b1f5',
        cover:"cover"
    },
    {
        id:7,
        nombre:'Descarga de datos meteorológicos',
        titulo:"DESCARGA DE DATOS METEOROLÓGICOS",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Descarga de los datos de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglacial del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2FDescarDEM_PT2.JPG?alt=media&token=b6a5ed42-b665-43e5-a318-75ae96456e9a',
        cover:"cover"
    },
    {
        id:8,
        nombre:'Fotogrametría terrestre con cámara multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE CON CÁMARA MULTIESPECTRAL",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la zona periglacial del glaciar Gueshgue para el monitoreo de la dinámica se su frente glaciar.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.FotogGueshgue_PT2.JPG?alt=media&token=380e3d6a-3963-48e7-8d5f-9187dcd2588e',
        cover:"cover"
    },
    {
        id:9,
        nombre:'Fotogrametría aérea RPA (dron)',
        titulo:"FOTOGRAMETRÍA AÉREA RPA (DRON)",
        subTitulo:"Glaciar Jatunraju",
        descripcion:'Fotogrametría aérea RPA (dron) en el glaciar Jatunraju para el monitoreo de la dinámica de la lengua glaciar cubierta de detritos y escombros.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Nov, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8.Drone_JatunRaju_PT2.JPG?alt=media&token=b5c1b65d-4f7a-4af3-baf9-14664c4750ed',
        cover:"cover"
    },
    {
        id:10,
        nombre:'Medición de caudales ',
        titulo:"MEDICIÓN DE CAUDALES",
        subTitulo:"Río Utcuyacu",
        descripcion:'Medición de caudales en el río Utcuyacu a través del método del correntómetro para la recolección de datos para el modelamiento hidrológico.',
        lugar:'Unidad hidrográfica Utcuyacu',
        fecha:'Feb, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8Aforo_Utcuyacu_toma_PT2.JPG?alt=media&token=33fa915e-f69b-47d7-bc51-aa1376506091',
        cover:"cover"
    },
    {
        id:11,
        nombre:'Instalación de balizas',
        titulo:"INSTALACIÓN DE BALIZAS",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Instalación de balizas en la zona de ablación en la parte media baja del glaciar Gueshgue, donde, se aprecia la laguna Pamparaju.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F3.BalizasGueshgue_PT2.JPG?alt=media&token=25c3ada8-8cba-4124-8d59-861b2e8308c3',
        cover:"cover"
    },
    {
        id:12,
        nombre:'Fotogrametría terrestre multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE MULTIESPECTRAL",
        subTitulo:"Laguna Llaca",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la parte lateral izquierda de la morrena de la laguna Llaca para el monitoreo de la dinámica del frente del glaciar Llaca.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.FotogLlaca_PT2.JPG?alt=media&token=06f2f343-63f9-4796-aa39-8f127bfab142',
        cover:"cover"
    },
    {
        id:13,
        nombre:'Fotogrametría terrestre multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE MULTIESPECTRAL",
        subTitulo:"Laguna Llaca",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la parte lateral izquierda de la morrena de la laguna Llaca para el monitoreo de la dinámica del frente del glaciar Llaca.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8.GPRArtesonraju2_PT2.JPG?alt=media&token=524a4747-0763-44c3-8c0b-ebe450ba7bd4',
        cover:"cover"
    },
]
export const listaPT4 = [
    {
        id:1,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes del INAIGEM y del SENAMHI.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller.jpeg?alt=media&token=8f89e190-084b-42b0-98e8-1439694a489e',
        cover:"cover-galeria"
    },
    {
        id:2,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes de la PUCP y los investigadores del Reino Unido.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller2.jpeg?alt=media&token=7357b7df-fae3-466f-91a5-2fdb53836256',
        cover:"cover"
    },
    {
        id:3,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Este taller se realizó como un primer encuentro para definir los alcances y las estrategias de mitigación y adaptación ante la inseguridad hídrica.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller4.jpeg?alt=media&token=ee1b0997-a23a-4e28-b336-a4020d8568a8',
        cover:"cover"
    },
    {
        id:4,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes de la PUCP y el INAIGEM.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller5.jpeg?alt=media&token=5af0122a-176d-4182-bc80-ab82342e0c79',
        cover:"cover"
    },
    {
        id:5,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Se aprecia a los líderes del proyecto Perú GROWS de la entidad ejecutora peruana el MSc. Edwin Loarte y de la entidad ejecutora del Reino Unido la PhD. Francesca Pelliciotti.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller6.jpeg?alt=media&token=c55daa6b-0062-4c27-b867-24e09608ea75',
        cover:"cover"
    },
    {
        id:6,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Exposición del PhD. Adebayo Adeloye de las BAS sobre las estrategias de mitigación y adaptación ante la inseguridad hídrica.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller_adebayo.jpeg?alt=media&token=d5ed0112-9454-469b-b733-406d4dd5d9f0',
        cover:"cover"
    }
]

export const listaPaisajes = [
    {
        id:1,
        nombre:'Unidad hidrográfica Yanayacu',
        titulo:"UNIDAD HIDROGRÁFICA YANAYACU",
        subTitulo:"Unidad hidrográfica Yanayacu",
        descripcion:"Vista panorámica de la cordillera Blanca desde la parte baja de la unidad hidrográfica Yanayacu, donde, se aprecian los ecosistemas de pastizal y un canal de regadío de tierra para las actividades económicas circundantes.",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FCanalBajo_Yanayacu_19.jpeg?alt=media&token=0c107943-0973-42c0-85dd-398463a8609d',
        cover:"cover"
    },
    {
        id:2,
        nombre:'Cumbre del glaciar Gueshgue',
        titulo:"CUMBRE DEL GLACIAR GUESHGUE",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica desde la cumbre del glaciar Gueshgue. Es la primera expedición en coronar la cumbre de dicho glaciar, que se realizó el 19 de octubre del 2020 por los expedicionistas Edwin Loarte y Francisco Castillo en compañía de los porters Romaldo Santiago y Federico Huane.",
        lugar:'Unidad hidrográfica Yanayacu ',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FCumbre_Gueshgue_20.jpeg?alt=media&token=e25af0d9-9fcf-4e66-8b3c-f037b9570643',
        cover:"cover"
    },
    {
        id:3,
        nombre:'Estación meteorológica de Artesonraju',
        titulo:"ESTACIÓN METEOROLÓGICA DE ARTESONRAJU",
        subTitulo:"Glaciar Artesonraju",
        descripcion:"Vista panorámica de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglaciar del glaciar Artesonraju.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FEstacionMet_Artesonraju_21.jpeg?alt=media&token=4b1558c6-6c18-4a42-aaec-fc08d9c58d02',
        cover:"cover"
    },
    {
        id:4,
        nombre:'Estación meteorológica de Gueshgue',
        titulo:"ESTACIÓN METEOROLÓGICA DE GUESHGUE",
        subTitulo:"Glaciar Gueshgue",
        descripcion:"Vista panorámica de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglaciar del glaciar Gueshgue. Así mismo, se aprecia la laguna en formación al pie del glaciar Gueshgue.",
        lugar:'Unidad hidrográfica Yanayacu ',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FEstacionMet_Gueshgue_20.jpeg?alt=media&token=bde998f3-7165-47f7-b3f4-c796ecde22fe',
        cover:"cover"
    },
    {
        id:5,
        nombre:'Estación meteorológica de Shallap',
        titulo:"ESTACIÓN METEOROLÓGICA DE SHALLAP",
        subTitulo:"Glaciar Shallap",
        descripcion:"Vista panorámica de la estación meteorológica del proyecto Perú GROWS ubicada en la parte lateral alta del glaciar Shallap. Así mismo, se aprecia el glaciar limpio y cubierto de detritos y escombros del glaciar Shallap.",
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FEstacionMet_Shallap_21.jpeg?alt=media&token=6f1236e3-290d-42c9-85b1-c5bc935b14b6',
        cover:"cover"
    },
    {
        id:6,
        nombre:'Glaciar Artesonraju 2019',
        titulo:"GLACIAR ARTESONRAJU 2019",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica dentro del glaciar Artesonraju en el año 2019, donde, se aprecia la laguna en formación en su lengua glaciar (Artesoncocha Alta) y el nevado Artesón.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Artesonraju_19.jpeg?alt=media&token=0a741d16-6361-46ff-8dcb-8ad954c87c86',
        cover:"cover"
    },
    {
        id:7,
        nombre:'Glaciar Artesonraju 2020',
        titulo:"GLACIAR ARTESONRAJU 2020",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica dentro del glaciar Artesonraju en el año 2020, donde, se aprecia la laguna en formación en su lengua glaciar (Artesoncocha Alta) y el nevado Artesón.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Artesonraju_20.jpeg?alt=media&token=63072706-1170-4afd-9bf5-339cf32a39a2',
        cover:"cover"
    },
    {
        id:8,
        nombre:'Glaciar Artesonraju 2021',
        titulo:"GLACIAR ARTESONRAJU 2021",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica dentro del glaciar Artesonraju en el año 2021, donde, se aprecia la laguna en formación en su lengua glaciar (Artesoncocha Alta) y el nevado Artesón.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Artesonraju_21.jpeg?alt=media&token=99ca6f13-2bbc-4052-8228-2a938c930d2a',
        cover:"cover"
    },
    {
        id:9,
        nombre:'Glaciar Gueshgue',
        titulo:"GLACIAR GUESHGUE",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica del frente del glaciar Gueshgue, donde, se aprecia la laguna en formación en su lengua glaciar.",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Gueshgue_20.jpeg?alt=media&token=04aca295-4bfd-4bc6-a8b9-b625612c4cf9',
        cover:"cover"
    },
    {
        id:10,
        nombre:'Glaciar Gueshgue',
        titulo:"GLACIAR GUESHGUE",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica dentro de la parte media alta del glaciar Gueshgue, donde, se aprecia la laguna 1376982-5 (izquierda), la laguna Pamparaju (derecha) y la laguna en formación (centro).",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Gueshgue_20_1.jpeg?alt=media&token=df9da9c8-c7be-4872-9239-90370c9d7e53',
        cover:"cover"
    },
    {
        id:11,
        nombre:'Glaciar Gueshgue',
        titulo:"GLACIAR GUESHGUE",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica dentro del glaciar Gueshgue, donde, se aprecia la laguna 1376982-5 (izquierda) y la laguna en formación.",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Gueshgue_20_2.jpeg?alt=media&token=9bb56216-397f-4a62-8bf0-20ba974908ed',
        cover:"cover"
    },
    {
        id:12,
        nombre:'Glaciar Jatunraju',
        titulo:"GLACIAR JATUNRAJU",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica dentro del glaciar Jatunraju, donde, se aprecia la extensión y forma de la parte del glaciar cubierto de detritos y escombros del glaciar.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Jatunraju_20.jpeg?alt=media&token=c089c958-22ec-4720-bc5f-02db02564014',
        cover:"cover"
    },
    {
        id:13,
        nombre:'Glaciar Llaca',
        titulo:"GLACIAR LLACA",
        subTitulo:"Quebrada Llaca",
        descripcion:"Vista panorámica del frente del glaciar Casca, donde, se aprecia la laguna en formación en su lengua glaciar, el glaciar limpio y cubierto de detritos y escombros.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Llaca_20.jpeg?alt=media&token=f3996065-cd74-452b-921e-c2203685435f',
        cover:"cover"
    },
    {
        id:14,
        nombre:'Glaciar Llaca',
        titulo:"GLACIAR LLACA",
        subTitulo:"Quebrada Llaca",
        descripcion:"Vista panorámica de la pared del glaciar Llaca ubicada en la parte final de la lengua glaciar.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Llaca_20_1.jpeg?alt=media&token=820f2bd1-e5ba-412e-b317-e0c365cf799e',
        cover:"cover"
    },
    {
        id:15,
        nombre:'Fotogrametría aérea RPA (dron)',
        titulo:"FOTOGRAMETRÍA AÉREA RPA (DRON)",
        subTitulo:"Glaciar Llaca",
        descripcion:"Fotogrametría aérea RPA (dron) en el glaciar Llaca para el monitoreo de la dinámica de la lengua glaciar cubierta de detritos y escombros, y la formación de lagunas supgraglaciares.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Llaca_20_2.jpeg?alt=media&token=f4eec411-269d-4f38-8e5e-c98042eabb14',
        cover:"cover"
    },
    {
        id:16,
        nombre:'Glaciar Shallap',
        titulo:"GLACIAR SHALLAP",
        subTitulo:"Quebrada Shallap",
        descripcion:"Vista panorámica desde la parte media de la superficie del glaciar limpio (izquierda) y cubierto de detritos y escombros (derecha) del glaciar Shallap.",
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Shallap_20.jpeg?alt=media&token=77d4ec3a-3fe1-4713-8cff-220e0f4dec27',
        cover:"cover"
    },
    {
        id:17,
        nombre:'Glaciar Shallap',
        titulo:"GLACIAR SHALLAP",
        subTitulo:"Quebrada Shallap",
        descripcion:"Vista panorámica de la parte media baja de la superficie del glaciar limpio y cubierto de detritos y escombros del glaciar Shallap, desde el mirador ubicado en la parte lateral derecha de la quebrada.",
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Shallap_20_2.jpeg?alt=media&token=3e1e184d-d341-40d5-9d0f-901331bf471d',
        cover:"cover"
    },
    {
        id:18,
        nombre:'Glaciar Shallap',
        titulo:"GLACIAR SHALLAP",
        subTitulo:"Quebrada Shallap",
        descripcion:"Vista panorámica de la parte alta de la superficie del glaciar limpio y cubierto de detritos y escombros del glaciar Shallap, desde el mirador ubicado en la parte lateral derecha de la quebrada.",
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FGlaciar_Shallap_21.jpeg?alt=media&token=93129468-f3db-4e9d-97f0-8b7b18c08b29',
        cover:"cover"
    },
    {
        id:19,
        nombre:'Laguna Artesoncocha',
        titulo:"LAGUNA ARTESONCOCHA",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica de la laguna Artesoncocha desde el mirador ubicado en la parte alta de la quebrada en el camino al glaciar Artesonraju.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Artesoncocha_19.jpeg?alt=media&token=2b3f2dd6-b6a6-4e5c-995e-0143af078425',
        cover:"cover"
    },
    {
        id:20,
        nombre:'Laguna Chacarhuayoc',
        titulo:"LAGUNA CHACARHUAYOC",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica de la laguna Chacarhuayoc ubicado en la parte baja de la quebrada Gueshgue.",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Chacarhuayoc_20.jpeg?alt=media&token=df48ae20-b32c-4fe8-9dc0-b24bacee72f3',
        cover:"cover"
    },
    {
        id:21,
        nombre:'Laguna Chacra',
        titulo:"LAGUNA CHACRA",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica de la laguna Chacra ubicada en la parte media alta de la quebrada Parón al pie del glaciar Pirámide 1.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Chacraraju_20.jpeg?alt=media&token=d462118c-958a-4666-8d4c-a5ddba867c9e',
        cover:"cover"
    },
    {
        id:22,
        nombre:'Laguna Llaca',
        titulo:"LAGUNA LLACA",
        subTitulo:"Quebrada Llaca",
        descripcion:"Vista panorámica de la laguna y el glaciar Llaca desde el mirador ubicado en la morrena derecha de la laguna.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Llaca_20.jpeg?alt=media&token=e6595b6d-0ad7-47cb-a2ba-6d3eba811230',
        cover:"cover"
    },
    {
        id:23,
        nombre:'Laguna Parón',
        titulo:"LAGUNA PARÓN",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica de la laguna Parón desde el mirador ubicado en la morrena del glaciar Jatunraju.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Nov, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Paron_20.jpeg?alt=media&token=53fea57d-1445-4f1d-bcf2-81e581be1fb3',
        cover:"cover"
    },
    {
        id:24,
        nombre:'Laguna Parón y nevado Pirámide',
        titulo:"LAGUNA PARÓN Y NEVADO PIRÁMIDE",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica de la laguna Parón y del nevado Pirámide desde la parte baja de la laguna Parón.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Paron_20_1.jpeg?alt=media&token=b9adea2a-9f91-4169-a3c7-deed0fbea046',
        cover:"cover"
    },
    {
        id:25,
        nombre:'Laguna Parón',
        titulo:"LAGUNA PARÓN",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica de la laguna Parón desde la parte trasera en el mirador ubicado en el camino a la laguna Chacra.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FLag_Paron_20_2.jpeg?alt=media&token=c8f9ea0f-ff97-47b4-9053-f9be6ed2021b',
        cover:"cover"
    },
    {
        id:26,
        nombre:'Nevado Artesón',
        titulo:"NEVADO ARTESÓN",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica del nevado Artesón ubicado en la parte alta de la quebrada y al costado izquierdo del glaciar Artesonraju.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FNevado_Arteson_20_1.jpeg?alt=media&token=47f7ecc4-1b7a-4e60-9fba-5f57e6afddf2',
        cover:"cover"
    },
    {
        id:27,
        nombre:'Nevado Pirámide',
        titulo:"NEVADO PIRÁMIDE",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica del nevado Pirámide ubicado en la parte alta de la quebrada y al costado derecho del glaciar Pirámide 1.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FNevado_Piramide_20.jpeg?alt=media&token=0aee5e18-8c93-47df-9a6c-054045dd32b0',
        cover:"cover"
    },
    {
        id:28,
        nombre:'Ingreso al nevado Pastoruri',
        titulo:"INGRESO AL NEVADO PASTORURI",
        subTitulo:"Quebrada Pastoruri",
        descripcion:"Vista panorámica del ingreso a la caminata hacia el nevado Pastoruri.",
        lugar:'Unidad hidrográfica Pachacoto',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FPControl_Pastoruri_19.jpeg?alt=media&token=cd3616e5-cdc9-46bd-99cb-34140b38b997',
        cover:"cover"
    },
    {
        id:29,
        nombre:'Puyas Raimondi de Pastoruri',
        titulo:"PUYAS RAIMONDI DE PASTORURI",
        subTitulo:"Quebrada Pastoruri",
        descripcion:"Vista panorámica del bosque de puyas Raimondi ubicada en la carretera hacia el nevado Pastoruri.",
        lugar:'Unidad hidrográfica Pachacoto',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FPuyas_Gueshgue_21.jpeg?alt=media&token=e1a374e7-2b6e-4733-85d5-7eec8f3c5571',
        cover:"cover"
    },
    {
        id:30,
        nombre:'Puyas Raimondi de Pastoruri',
        titulo:"PUYAS RAIMONDI DE PASTORURI",
        subTitulo:"Quebrada Pastoruri",
        descripcion:"Vista panorámica de las puyas Raimondi y los ecosistemas de pastizal ubicadas en la carretera hacia el nevado Pastoruri.",
        lugar:'Unidad hidrográfica Pachacoto',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FPuyas_Pastoruri_19.jpeg?alt=media&token=782a72cf-f5ab-4c16-a224-070354df106e',
        cover:"cover"
    },
    {
        id:31,
        nombre:'Quebrada Gueshgue',
        titulo:"QUEBRADA GUESHGUE",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica de la quebrada Gueshgue en la trayectoria hacia el glaciar, se aprecia el bosque de puyas Raimondi, la laguna y los ecosistemas de pastizal de la quebrada.",
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FQuebrada_Gueshgue_20.jpeg?alt=media&token=5655854c-e579-4e34-9e64-07b89e470863',
        cover:"cover"
    },
    {
        id:32,
        nombre:'Quebrada Llaca',
        titulo:"QUEBRADA LLACA",
        subTitulo:"Quebrada Llaca",
        descripcion:"Vista panorámica de la quebrada Llaca desde la trayectoria a la laguna, se aprecia los bosques de quenuales y los ecosistemas de pastizal de la quebrada.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FQuebrada_Llaca_21.jpeg?alt=media&token=5e32c86a-e309-4ae7-b5c2-1b982fb59020',
        cover:"cover"
    },
    {
        id:33,
        nombre:'Quebrada Shallap',
        titulo:"QUEBRADA SHALLAP",
        subTitulo:"Quebrada Shallap",
        descripcion:"Vista panorámica de la quebrada Shallap desde la trayectoria hacia el glaciar, se aprecia los bosques de quenuales, los ecosistemas de pastizal de la quebrada y la laguna Shallap.",
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FQuebrada_Shallap_20.jpeg?alt=media&token=c68ffce9-c616-4d2f-9e5c-db1279221cbc',
        cover:"cover"
    },
    {
        id:34,
        nombre:'Río de Artesoncocha Alta',
        titulo:"RÍO DE ARTESONCOCHA ALTA",
        subTitulo:"Quebrada Parón",
        descripcion:"Vista panorámica del río que nace de la laguna en formación al pie del glaciar Artesonraju, donde, se aprecia el puente de madera y debajo, el registrador de nivel de agua instalado por el proyecto Perú GROWS.",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FRio_Artesonraju_20.jpeg?alt=media&token=5d93a60e-c753-457a-9eb4-0de344e7d1a1',
        cover:"cover"
    },
    {
        id:35,
        nombre:'Río de Pamaparaju',
        titulo:"RÍO DE PAMAPARAJU",
        subTitulo:"Quebrada Gueshgue",
        descripcion:"Vista panorámica del río que nace de la laguna Pamparaju en la parte alta de la quebrada, donde, se aprecia el registrador de nivel de agua instalado por el proyecto Perú GROWS.",
        lugar:'Unidad hidrográfica Gueshgue',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FRio_Gueshgue_20.jpeg?alt=media&token=3b94773c-4bbc-4633-9313-ac81d6df8fe5',
        cover:"cover"
    },
    {
        id:36,
        nombre:'Río de Llaca',
        titulo:"RÍO DE LLACA",
        subTitulo:"Quebrada Llaca",
        descripcion:"Vista panorámica del río canalizado que nace de la laguna Llaca en la parte alta de la quebrada.",
        lugar:'Unidad hidrográfica Casca',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FRio_Llaca_16.jpeg?alt=media&token=7c56df1c-79c5-48c9-a55e-f9d71524a8af',
        cover:"cover"
    },
    {
        id:37,
        nombre:'Medición de espesor de hielo (GPR)',
        titulo:"MEDICIÓN DE ESPESOR DE HIELO (GPR)",
        subTitulo:"Glaciar Artesonraju",
        descripcion:"Medición del espesor de hielo usando el equipo radar de penetración terrestre (GPR) en la superficie del glaciar limpio de Artesonraju (parte media) para el monitoreo de la variación de la profundidad del hielo glaciar y su potencial de reserva hídrica (año 2020).",
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpaisajes%2FRio_Shallap_20.jpeg?alt=media&token=9fda7031-82c6-4677-94c5-365dcc044241',
        cover:"cover"
    },
]

export const listaTodo = [
    {
        id:1,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Caraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con la población de la unidad hidrográfica Llullán realizado en la ciudad de Caraz teniendo como expositor al co-investigador Fernando González de la entidad asociada de la PUCP.',
        lugar:'Unidad hidrográfica Llullán	',
        fecha:'Jun, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F2.taller_llull%C2%A0n.JPG?alt=media&token=0642ecb3-0bcd-4c18-b30a-1ca04e83e305',
        cover:"cover"
    },
    {
        id:2,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz teniendo como expositores a los investigadores principales Edwin Loarte y Francesca Pelliciotti.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.Workshop_taller_centro_cultural.jpg?alt=media&token=48d33f74-fa21-49b1-8808-a93b13330b02',
        cover:"cover"
    },
    {
        id:3,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.Workshop_taller_centro_cultural3.jpg?alt=media&token=09341e2c-15ee-45e6-9f50-bae3de072009',
        cover:"cover"
    },
    {
        id:4,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Cátac",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidad hidrográfica Yanayacu realizado en el auditorio de la Municipalidad Distrital de Cátac.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac.JPG?alt=media&token=ab86394e-216d-42af-9f33-fd0e7afc1356',
        cover:"cover"
    },
    {
        id:5,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Cátac",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidad hidrográfica Yanayacu realizado en el auditorio de la Municipalidad Distrital de Cátac.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac3.JPG?alt=media&token=407ba6b2-a766-476b-8f74-54ed59136aee',
        cover:"cover"
    },
    {
        id:6,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Camino a Pastoruri",
        descripcion:'Taller de campo de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el ruta del cambio climático del nevado Pastoruri.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F6.Workshop_taller_catac4.JPG?alt=media&token=251160a5-44d3-44cc-a72a-a25065778b69',
        cover:"cover"
    },
    {
        id:7,
        nombre:'Taller de sociabilización del proyecto',
        titulo:"TALLER DE SOCIABILIZACIÓN DEL PROYECTO",
        subTitulo:"Ciudad de Huaraz",
        descripcion:'Taller de sociabilización del proyecto Perú GROWS con las autoridades locales de la unidades hidrográficas Llullán, Quillcay Yanayacu realizado en el centro cultural de la ciudad de Huaraz.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2FWorkshop_taller_centro_cultural2.jpeg?alt=media&token=66d14447-e3fc-483a-b791-087606485d7e',
        cover:"cover"
    },
    {
        id:8,
        nombre:'Monitoreo de la calidad de agua',
        titulo:"MONITOREO DE LA CALIDAD DE AGUA",
        subTitulo:"Río de Artesoncocha Alta",
        descripcion:'Monitoreo de la calidad de agua en la parte media del río que fluye de la laguna en formación al pie del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán ',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F1.Calidad_Artesonraju_PT1.jpg?alt=media&token=27a4fe19-bef3-4b0f-8cdf-794eb5376c85',
        cover:"cover"
    },
    {
        id:9,
        nombre:'Monitoreo de la calidad de agua',
        titulo:"MONITOREO DE LA CALIDAD DE AGUA",
        subTitulo:"Laguna Artesoncocha Alta",
        descripcion:'Monitoreo de la calidad de agua en la laguna en formación al pie del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán ',
        fecha:'Jul, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F4.Calidad_Artesonraju_PT1.JPG?alt=media&token=e9b8bbc8-7bb6-4335-a618-971319132688',
        cover:"cover"
    },
    {
        id:10,
        nombre:'Muestreo de macroinvertebrados',
        titulo:"MUESTREO DE MACROINVERTEBRADOS",
        subTitulo:"Río de Llaca",
        descripcion:'Muestreo de macroinvertebrados con el uso de una malla surber en el río de salida de la laguna Llaca para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F4.MacroinvertebradosLlaca_PT1.JPG?alt=media&token=f978a311-42c7-4de7-b534-345c50ae7c43',
        cover:"cover"
    },
    {
        id:11,
        nombre:'Muestreo de macroinvertebrados',
        titulo:"MUESTREO DE MACROINVERTEBRADOS",
        subTitulo:"Río de Pamparaju",
        descripcion:'Muestreo de macroinvertebrados con el uso de una malla surber en el río de salida de la laguna Pamparaju para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F5.MacroInv_Gueshgue20_PT1.JPG?alt=media&token=fa922fb1-264b-411d-bd75-70112510cc85',
        cover:"cover"
    },
    {
        id:12,
        nombre:'Muestreo de algas y diatomeas',
        titulo:"MUESTREO DE ALGAS Y DIATOMEAS",
        subTitulo:"Río de Pamparaju",
        descripcion:'Muestreo de algas y diatomeas en el río de salida de la laguna Pamparaju para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F8.Diatomeas_Gueshgue20_PT1.JPG?alt=media&token=f06fb4e5-77f9-4a10-a628-0e1eb46580dd',
        cover:"cover"
    },
    {
        id:13,
        nombre:'Muestreo de algas y diatomeas',
        titulo:"MUESTREO DE ALGAS Y DIATOMEAS",
        subTitulo:"Río de laguna en formación de Gueshgue",
        descripcion:'Muestreo de algas y diatomeas en el río de salida de la laguna en formación al pie del glaciar Gueshgue para el monitoreo de la biodiversidad y el estado actual de los ecosistemas.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt1%2F10.Diatomeas_Gueshgue20_PT1.JPG?alt=media&token=378e30c7-3da9-4fea-9acd-028556507650',
        cover:"cover"
    },
    {
        id:14,
        nombre:'Medición de espesor de hielo (GPR)',
        titulo:"MEDICIÓN DE ESPESOR DE HIELO (GPR)",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Medición del espesor de hielo usando el equipo radar de penetración terrestre (GPR) en la superficie del glaciar limpio de Gueshgue (parte media) para el monitoreo de la variación de la profundidad del hielo glaciar y su potencial de reserva hídrica (año 2021).',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F10.GPR_Gueshgue21.JPG?alt=media&token=9c33198d-0e1c-467d-9e76-cc67cdd8948d',
        cover:"cover"
    },
    {
        id:15,
        nombre:'Instalación de balizas',
        titulo:"INSTALACIÓN DE BALIZAS",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Instalación de balizas en la zona de ablación en la parte media del glaciar Gueshgue para el monitoreo glaciológico.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F2.BalizasArtesonraju_PT2.JPG?alt=media&token=bce50076-deb8-4e1a-a5f1-51289720fc11',
        cover:"cover"
    },
    {
        id:16,
        nombre:'Medición de espesor de hielo (GPR)',
        titulo:"MEDICIÓN DE ESPESOR DE HIELO (GPR)",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Medición del espesor de hielo usando el equipo radar de penetración terrestre (GPR) en la superficie del glaciar limpio de Gueshgue (parte media) para el monitoreo de la variación de la profundidad del hielo glaciar y su potencial de reserva hídrica (año 2020).',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F4.GPRGueshgue3.JPG?alt=media&token=764bbac4-348c-49d9-bf20-92b2a45b1b98',
        cover:"cover"
    },
    {
        id:17,
        nombre:'Fotogrametría aérea RPA (dron)',
        titulo:"FOTOGRAMETRÍA AÉREA RPA (DRON)",
        subTitulo:"Glaciar Shallap",
        descripcion:'Fotogrametría aérea RPA (dron) en la parte alta del glaciar Shallap para el monitoreo de la dinámica de la lengua glaciar limpia y cubierta de detritos y escombros.',
        lugar:'Unidad hidrográfica Quillcay',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F5.FotogAerea_Shallap_PT2.jpg?alt=media&token=c10010c6-81b4-4d87-9674-555c90d05d8c',
        cover:"cover"
    },
    {
        id:18,
        nombre:'Instalación de estación meteorológica ',
        titulo:"INSTALACIÓN DE ESTACIÓN METEOROLÓGICA",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Instalación y configuración de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglacial del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2FMantEM_PT2.jpg?alt=media&token=cb83dd4b-35e5-4d50-a7d4-24b61f3458ff',
        cover:"cover"
    },
    {
        id:19,
        nombre:'Medición de caudales ',
        titulo:"MEDICIÓN DE CAUDALES",
        subTitulo:"Río de Artesoncocha Alta",
        descripcion:'Medición de caudales del río proveniente del desemboque de la laguna en formación al pie del glaciar Artesonraju, a través del método del correntómetro para la recolección de datos para el modelamiento hidrológico.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.Aforo_correntometro_Artesonraju2021_PT2.jpg?alt=media&token=630fe517-3ea0-48c5-8c42-f10a5520b1f5',
        cover:"cover"
    },
    {
        id:20,
        nombre:'Descarga de datos meteorológicos',
        titulo:"DESCARGA DE DATOS METEOROLÓGICOS",
        subTitulo:"Glaciar Artesonraju",
        descripcion:'Descarga de los datos de la estación meteorológica del proyecto Perú GROWS ubicada en la zona periglacial del glaciar Artesonraju.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Set, 2021',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2FDescarDEM_PT2.JPG?alt=media&token=b6a5ed42-b665-43e5-a318-75ae96456e9a',
        cover:"cover"
    },
    {
        id:21,
        nombre:'Fotogrametría terrestre con cámara multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE CON CÁMARA MULTIESPECTRAL",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la zona periglacial del glaciar Gueshgue para el monitoreo de la dinámica se su frente glaciar.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.FotogGueshgue_PT2.JPG?alt=media&token=380e3d6a-3963-48e7-8d5f-9187dcd2588e',
        cover:"cover"
    },
    {
        id:22,
        nombre:'Fotogrametría aérea RPA (dron)',
        titulo:"FOTOGRAMETRÍA AÉREA RPA (DRON)",
        subTitulo:"Glaciar Jatunraju",
        descripcion:'Fotogrametría aérea RPA (dron) en el glaciar Jatunraju para el monitoreo de la dinámica de la lengua glaciar cubierta de detritos y escombros.',
        lugar:'Unidad hidrográfica Llullán',
        fecha:'Nov, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8.Drone_JatunRaju_PT2.JPG?alt=media&token=b5c1b65d-4f7a-4af3-baf9-14664c4750ed',
        cover:"cover"
    },
    {
        id:23,
        nombre:'Medición de caudales ',
        titulo:"MEDICIÓN DE CAUDALES",
        subTitulo:"Río Utcuyacu",
        descripcion:'Medición de caudales en el río Utcuyacu a través del método del correntómetro para la recolección de datos para el modelamiento hidrológico.',
        lugar:'Unidad hidrográfica Utcuyacu',
        fecha:'Feb, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8Aforo_Utcuyacu_toma_PT2.JPG?alt=media&token=33fa915e-f69b-47d7-bc51-aa1376506091',
        cover:"cover"
    },
    {
        id:24,
        nombre:'Instalación de balizas',
        titulo:"INSTALACIÓN DE BALIZAS",
        subTitulo:"Glaciar Gueshgue",
        descripcion:'Instalación de balizas en la zona de ablación en la parte media baja del glaciar Gueshgue, donde, se aprecia la laguna Pamparaju.',
        lugar:'Unidad hidrográfica Yanayacu',
        fecha:'Oct, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F3.BalizasGueshgue_PT2.JPG?alt=media&token=25c3ada8-8cba-4124-8d59-861b2e8308c3',
        cover:"cover"
    },
    {
        id:25,
        nombre:'Fotogrametría terrestre multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE MULTIESPECTRAL",
        subTitulo:"Laguna Llaca",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la parte lateral izquierda de la morrena de la laguna Llaca para el monitoreo de la dinámica del frente del glaciar Llaca.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F6.FotogLlaca_PT2.JPG?alt=media&token=06f2f343-63f9-4796-aa39-8f127bfab142',
        cover:"cover"
    },
    {
        id:26,
        nombre:'Fotogrametría terrestre multiespectral',
        titulo:"FOTOGRAMETRÍA TERRESTRE MULTIESPECTRAL",
        subTitulo:"Laguna Llaca",
        descripcion:'Fotogrametría terrestre con cámara multiespectral desde la parte lateral izquierda de la morrena de la laguna Llaca para el monitoreo de la dinámica del frente del glaciar Llaca.',
        lugar:'Unidad hidrográfica Casca',
        fecha:'Set, 2020',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt2%2F8.GPRArtesonraju2_PT2.JPG?alt=media&token=524a4747-0763-44c3-8c0b-ebe450ba7bd4',
        cover:"cover"
    },
    {
        id:27,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes del INAIGEM y del SENAMHI.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller.jpeg?alt=media&token=8f89e190-084b-42b0-98e8-1439694a489e',
        cover:"cover-galeria"
    },
    {
        id:28,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes de la PUCP y los investigadores del Reino Unido.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller2.jpeg?alt=media&token=7357b7df-fae3-466f-91a5-2fdb53836256',
        cover:"cover"
    },
    {
        id:29,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Este taller se realizó como un primer encuentro para definir los alcances y las estrategias de mitigación y adaptación ante la inseguridad hídrica.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller4.jpeg?alt=media&token=ee1b0997-a23a-4e28-b336-a4020d8568a8',
        cover:"cover"
    },
    {
        id:30,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Mesa de trabajo entre integrantes de la PUCP y el INAIGEM.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller5.jpeg?alt=media&token=5af0122a-176d-4182-bc80-ab82342e0c79',
        cover:"cover"
    },
    {
        id:31,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Se aprecia a los líderes del proyecto Perú GROWS de la entidad ejecutora peruana el MSc. Edwin Loarte y de la entidad ejecutora del Reino Unido la PhD. Francesca Pelliciotti.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller6.jpeg?alt=media&token=c55daa6b-0062-4c27-b867-24e09608ea75',
        cover:"cover"
    },
    {
        id:32,
        nombre:'Taller de trabajo del proyecto',
        titulo:"TALLER DE TRABAJO DEL PROYECTO",
        subTitulo:"Hotel Churup",
        descripcion:'Primer taller de trabajo entre las entidades asociadas del proyecto Perú GROWS realizado en el hotel Churup en la ciudad de Huaraz. Exposición del PhD. Adebayo Adeloye de las BAS sobre las estrategias de mitigación y adaptación ante la inseguridad hídrica.',
        lugar:'Ciudad de Huaraz',
        fecha:'Ago, 2019',
        url:'https://firebasestorage.googleapis.com/v0/b/proyecto-perugrows.appspot.com/o/galeria%2Fpt4%2FWorkshop_taller_adebayo.jpeg?alt=media&token=d5ed0112-9454-469b-b733-406d4dd5d9f0',
        cover:"cover"
    }
]