import Head from 'next/head';
import Layout from '../../src/layout';
import Nav from '../../src/components/shared/nav/nav';
import React from 'react';
import Index from '../../src/components/produccion/index';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Perú GROWS - INAIGEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/inaigem.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
      </Head>
      <main>
        <Nav />
        <Index />
      </main>
    </Layout>
  )
}