import Head from 'next/head';
import Layout from '../../src/layout';
import NavShared from '../../src/components/shared/nav/nav.shared';
import Index from '../../src/components/equipo/index';
import Footer from '../../src/components/shared/footer/footer';
import React from 'react';

export default function TeamCientific(){
   
    return(
        <Layout>
            <Head>
                <title>Permafrost - INAIGEM</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/inaigem.ico" />
            </Head>
            <main>
                <NavShared />
                <Index />
                <Footer />
            </main>
        </Layout>
    );
}